### ISSUE TITLE
Replace libev with libuv

### ISSUE THREAD

**Issue by theoparis** [yshui/compton#1222] opened 2024-03-24 22:22 UTC
It seems like the github repository for libev hasn't been updated for 8 years, and there is a PR that [fixes compatibility with C++17 that will never be merged due to the github repository being unmaintained](https://github.com/enki/libev/pull/8). Additionally, libev seems to have design issues - I tried to fork it but it turns out the ev_loop struct is defined in a C file instead of a .h file and it is hard to move it to the h file without rewriting the macro system it uses. Additionally, the libev website only supports http 😬

Example of the design issues from there being no struct defined in ev.h:
![image](https://github.com/yshui/picom/assets/11761863/ec3a8395-75a8-406b-99cf-2902cc0bbc6e)

**Comment by yshui** [comment] 2024-03-25 09:38
None of the things you quoted are problems of libev. Not exposing ev_loop in headers is a common C design pattern (read about it here: https://en.wikipedia.org/wiki/Opaque_pointer)

If we actually found a bug in libev, then replacing it would become necessary. I don't see a point for now.

**Comment by yshui** [comment] 2024-03-25 09:39
Also duplicate of #1163

**Closed as not planned by yshui** 2024-03-25 09:38 UTC
