### ISSUE TITLE
High CPU usage on NVIDIA when screen is off with GLX backend, vsync and frame pacing enabled

### ISSUE THREAD

**Issue by bubbleguuum** [yshui/compton#1367] opened 2024-10-17 10:04 UTC
### Platform

openSUSE Tumbleweed as of the date of this report

### GPU, drivers, and screen setup

- NVIDIA Quadro P600 using  NVIDIA drivers 550.120

Using a laptop connected to an external monitor via mini-DP port. 
Laptop internal panel is off, external monitor is on and managed by the NVIDIA card:

```
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 3168 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: Quadro P600/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 550.120
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 550.120
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 550.120
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment

- i3 window manager

### picom version

```
**Version:** v12.3

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file specified: None
* Config file used: /home/bobbie/.config/picom/picom.conf

### Drivers (inaccurate):

NVIDIA, Intel

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: Quadro P600/PCIe/SSE2
[ 10/17/2024 11:50:05.179 egl_init WARN ] The egl backend is still experimental, use with care.

### Backend: egl

* Driver vendors:
 * EGL: NVIDIA
 * GL: NVIDIA Corporation
* GL renderer: Quadro P600/PCIe/SSE2
```

### Configuration:

```
backend = "glx"
vsync = true
```

### Steps of reproduction

With the `glx` backend and vsync enabled in config, whenever I turn my monitor off via DPMS (using  `xset dpms force off` that I bound to a keyboard shortcut), picom will take high cpu usage in the 50-80% range.
Sometimes, if I leave the monitor off long enough, it will take 100% CPU usage, and when I wake up the screen Xorg is unusable and unresponsive. I have to kill picom.

This issue does not happen with `vsync = false`, thus it is vsync specific. Also, it does not happen with  `vsync = true` used in conjunction with frame pacing disabled (`no-frame-pacing = true`).
Thus this issue is probably NVIDIA specific with vsync and frame pacing enabled, with something not working right in the frame pacing handling when the screen is off.

**Comment by yshui** [comment] 2024-10-17 11:33
probable duplicate of #1265 

can you have a look at that issue?

**Comment by bubbleguuum** [comment] 2024-10-17 11:56
Confirming it is the same issue. When the screen is off, console is spammed with these messages in a busy loop:


```
[ 10/17/2024 13:54:50.616 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.616 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.629 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.629 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.642 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.642 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.656 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.656 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.669 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.669 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.682 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.682 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.695 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.695 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.708 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.708 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.722 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.722 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.735 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.735 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.748 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.748 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.762 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.762 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.775 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.775 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.788 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.788 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.802 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.802 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.815 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.815 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.828 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
[ 10/17/2024 13:54:50.828 sgi_video_sync_scheduler_callback WARN ] Resetting the vblank scheduler
[ 10/17/2024 13:54:50.841 sgi_video_sync_scheduler_callback WARN ] Duplicate vblank event found with msc 0. Possible NVIDIA bug?
```

**Comment by bubbleguuum** [comment] 2024-10-17 12:00
And as expected, starting picom with `PICOM_DEBUG=force_vblank_sched=present` does not trigger that busy loop.

Question: shouldn't picom be entirely idle (doing nothing) when the screen is off ? Like not managing vblank at all ?

**Comment by yshui** [comment] 2024-10-17 12:18
picom doesn't actively check if the screen is off.

let's continue the discussion in #1265

**Closed as not planned by yshui** 2024-10-17 12:18 UTC
