### ISSUE TITLE
10 bit colour depth breaks picom ?

### ISSUE THREAD

**Issue by NicTanghe** [yshui/compton#1286] opened 2024-07-02 17:08 UTC
### Platform
RHEL 9/4

### GPU, drivers, and screen setup
NVIDIA  550 propertiery

### picom version

<details>
<summary>Diagnostics</summary>
```
❯ picom --diagnostics
[ 07/02/2024 19:03:36.526 parse_config_libconfig WARN ] The refresh-rate option has been deprecated. Please remove it from your configuration file. If you encounter any problems without this feature, please feel free to open a bug report
[ 07/02/2024 19:03:36.526 c2_parse_target WARN ] Type specifier is deprecated. Type "c" specified on target "_GTK_FRAME_EXTENTS" will be ignored, you can remove it.
[ 07/02/2024 19:03:36.526 c2_parse_target WARN ] Type specifier is deprecated. Type "a" specified on target "_NET_WM_STATE" will be ignored, you can remove it.
[ 07/02/2024 19:03:36.526 c2_parse_target WARN ] Format specifier is deprecated. Format "32" specified on target "_NET_WM_STATE" will be ignored, you can remove it.
[ 07/02/2024 19:03:36.526 c2_parse_target WARN ] Type specifier is deprecated. Type "c" specified on target "_GTK_FRAME_EXTENTS" will be ignored, you can remove it.
**Version:** vgit-a0e81

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file specified: None
* Config file used: /home/tanghe/.config/picom/picom.conf

### Drivers (inaccurate):

NVIDIA
[ 07/02/2024 19:03:36.541 egl_init WARN ] The egl backend is still experimental, use with care.
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
[ 07/02/2024 19:03:36.661 eglext_init INFO ] Extension EGL_EXT_buffer_age - absent
[ 07/02/2024 19:03:36.661 eglext_init INFO ] Extension EGL_EXT_create_context_robustness - present
[ 07/02/2024 19:03:36.661 eglext_init INFO ] Extension EGL_KHR_image_pixmap - absent
[ 07/02/2024 19:03:36.661 eglext_init INFO ] Extension EGL_MESA_query_driver - present
[ 07/02/2024 19:03:36.661 egl_init ERROR ] EGL_KHR_image_pixmap not available.
 Cannot initialize backend egl

picom: ../src/dispatch_common.c:858: epoxy_get_proc_address: Assertion `0 && "Couldn't find current GLX or EGL context.\n"' failed.
zsh: IOT instruction (core dumped)  picom --diagnostics
<!-- Please also include the output of `picom --diagnostics` -->
</details>
```
### Configuration:
<details>
    <summary>Configuration file</summary>

```
Irrelavent
```
</details>

### Steps of reproduction

1. set your colourdepth to 10 in x
/etc/X11/xorg.conf.d/20-dci-p3.conf
```
Section "Device"
    Identifier "MyGPU"
    Driver "nvidia"  # or the appropriate driver for your GPU
EndSection

Section "Monitor"
    Identifier "HPMonitor"
    Option "DPMS"
EndSection

Section "Monitor"
    Identifier "SamsungMonitor"
    Option "DPMS"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "MyGPU"
    Monitor "HPMonitor"
    DefaultDepth 30
    SubSection "Display"
        Depth 30
    EndSubSection
EndSection

Section "Screen"
    Identifier "Screen1"
    Device "MyGPU"
    Monitor "SamsungMonitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
    EndSubSection
EndSection

```
2.

[ 07/02/2024 19:01:40.868 glx_init ERROR ] Root visual lacks stencil buffer.
picom: ../src/dispatch_common.c:858: epoxy_get_proc_address: Assertion `0 && "Couldn't find current GLX or EGL context.\n"' failed.
zsh: IOT instruction (core dumped)  picom
experience things not working

### Expected behavior
works
### Current Behavior
doesn`t work

not perhaps the way i setup 
/etc/X11/xorg.conf.d/20-dci-p3.conf

is just wrong

**Comment by absolutelynothelix** [comment] 2024-07-02 17:25
more like 10 bpp breaks x therefore picom is broken too. i did some investigation in #158 a while ago and i don't think there's something we can do unless i missed something and wrong.

**Comment by yshui** [comment] 2024-07-02 21:13
@absolutelynothelix i don't think we need the stencil buffer? what happens if we just remove the check

**Comment by yshui** [comment] 2024-07-02 21:14
Let's move the discussion to #158 

Duplicate of #158

**Closed as completed by yshui** 2024-07-02 21:14 UTC
