### ISSUE TITLE
Invalid extension event 161 & 146

### ISSUE THREAD

**Issue by ShadiestGoat** [yshui/compton#1249] opened 2024-04-25 20:30 UTC
### Platform
Arch, up to date

### GPU, drivers, and screen setup

NVIDIA GeForce GTX 1650 Ti Mobile, nvidia-dkms 550.76-2
Two monitors + xrandr
No xf86-video-\* drivers. optimus-manager installed.

```
glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 3279 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 550.76
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 550.76
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 550.76
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
sddm + bspwm

### picom version
v9 (git, latest commit)

<details>
<summary>Diagnostics</summary>
**Version:** v9

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/shady/.config/picom/picom.conf

### Drivers (inaccurate):

NVIDIA, modesetting

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
shadow = false;

corner-radius = 8;
rounded-corners-exclude = [
  "class_g = 'Polybar'"
];
round-borders = 8;

fading = true;
no-fading-openclose = false;
fade-in-step = 0.1;
fade-out-step = 0.1;
fade-delta = 9;

# nice kawase blur
blur: {
  method = "dual_kawase";
  strength = 3;
  background = false;
  background-frame = false;
  background-fixed = false;
}

backend = "glx";
vsync = true

mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-client-opacity = true;
detect-client-leader = true;

blur-background-exclude = [
  "class_g ?= 'zoom'",
  "name = 'rect-overlay'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'LibreWolf'",
  "window_type *= 'menu'",
#  "(class_g = 'Firefox' || class_g = 'Thunderbird') && (window_type = 'utility' || window_type = 'popup_menu') && argb",
#  "window_type = 'menu'",
#  "window_type = 'dropdown_menu'",
#  "window_type = 'popup_menu'",
#  "window_type = 'tooltip'",
];
```
</details>

### Steps of reproduction

1. Launch picom with my setup
2. Launch a new window & close it

### Expected behavior

No errors

### Current Behavior

Spam of the follow 2 errors:

Xlib: ignoring invalid extension event 161
Xlib: ignoring invalid extension event 146

### Other details

I am aware of [this PR](https://github.com/yshui/picom/pull/1075). Perhaps there was a regression?

**Comment by absolutelynothelix** [comment] 2024-05-05 15:50
your picom is severely outdated, the v9 release was made more than two years ago. the issue is already fixed and the fix is included since the v11-rc1 pre-release.

closing as duplicate of #1096.

**Closed as not planned by absolutelynothelix** 2024-05-05 15:50 UTC
Labels: duplicate
