### ISSUE TITLE
experimental xrender - unredir crash, the 2nd

### ISSUE THREAD

**Issue by aufkrawall** [yshui/compton#239] opened 2019-09-23 12:49 UTC
Hello yhsui,
as mentioned there, this issue is back since commit eecee130b8d7f5b5e9bb735a1e7979c35177729f
https://github.com/yshui/compton/issues/189

Attached is a debug log, crash dump and compton binary.
[compton.zip](https://github.com/yshui/compton/files/3642172/compton.zip)

**Comment by yshui** [comment] 2019-09-23 14:39
thanks.

this is related to getting a ShapeNotify in the same cycle the window is unmap, i haven't found the cause yet. if you can reproduce this with a debug build of compton, it would be helpful.

**Comment by aufkrawall** [comment] 2019-09-23 14:40
Yeah, I can reliably reproduce it simply by doing alt + tabbing out of vkquake.

**Comment by yshui** [comment] 2019-09-23 14:45
@aufkrawall can you attach the dump and binary from a debug build?

but i think i know where the problem is now, will fix once i get back to my computer.

**Comment by aufkrawall** [comment] 2019-09-23 14:50
Ah, yeah. I didn't enable debug build in meson.

**Comment by yshui** [comment] 2019-09-23 19:45
> Ah, yeah. I didn't enable debug build in meson.
Can you create a debug build?

**Comment by aufkrawall** [comment] 2019-09-23 20:07
> > Ah, yeah. I didn't enable debug build in meson.
> 
> Can you create a debug build?

Of course, stay tuned.

**Comment by aufkrawall** [comment] 2019-09-23 20:14
Same content as above, but with debug build:
[compton2.zip](https://github.com/yshui/compton/files/3643959/compton2.zip)

**Comment by yshui** [comment] 2019-09-23 20:56
@aufkrawall should've been fixed, can you try the latest `next`?

**Comment by aufkrawall** [comment] 2019-09-23 21:02
@yshui Haven't tested with the same AMD GPU system, but on my Intel notebook it still crashes.

**Comment by yshui** [comment] 2019-09-23 21:34
> @yshui <https://github.com/yshui> Haven't tested with the same AMD GPU
> system, but on my Intel notebook it still crashes.
>
that's odd, i cannot reproduce it anymore. could be a different crash?

can you attach the newer log/dump? thanks.

>

**Comment by aufkrawall** [comment] 2019-09-24 06:58
Here we go again:
[compton3.zip](https://github.com/yshui/compton/files/3645693/compton3.zip)

**Comment by yshui** [comment] 2019-09-24 20:38
i found the cause. it's because the window is unmapped the same cycle the screen is redirected, so it didn't get a chance to acquire the pixmap

solving this one will be a bit trickier

**Comment by yshui** [comment] 2019-09-28 23:41
@aufkrawall hopefully it's fixed now.

**Closed** 2019-09-28 23:40 UTC

**Comment by aufkrawall** [comment] 2019-09-29 07:20
@yshui Yep, issue's gone here.
Thanks once again. Having proper auto unredirect is really a great feature of Compton.
