### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by MrIvanPlays** [yshui/compton#921] opened 2022-11-14 12:03 UTC
### Platform
Arch Linux

### GPU, drivers, and screen setup
Nvidia GTX 1050Ti, nvidia-drivers 520.56.06, two monitors configured side-by-side with xrandr
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 3128 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 520.56.06
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 520.56.06
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 520.56.06
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### picom version: vgit-7d0d6

<details>
<summary>Diagnostics</summary>
**Version:** vgit-7d0d6

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/mrivanplays/.config/picom.conf

### Drivers (inaccurate):

NVIDIA

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

### Backend: egl

* Driver vendors:
 * EGL: NVIDIA
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
### Configuration:
<details>
    <summary>Configuration file</summary>

```                                            
#################################
#          Animations           #
#################################

animations: true;
animation-stiffness = 200
animation-window-mass = 0.4
animation-dampening = 20
animation-clamping = false
animation-for-open-window = "zoom"; #open window
animation-for-unmap-window = "zoom"; #minimize window
animation-for-workspace-switch-in = "slide-down"; #the windows in the workspace that is coming in
animation-for-workspace-switch-out = "zoom"; #the windows in the workspace that are coming out
animation-for-transient-window = "slide-up"; #popup windows

#################################
#             Shadows           #
#################################


# Enabled client-side shadows on windows. Note desktop windows 
# (windows with '_NET_WM_WINDOW_TYPE_DESKTOP') never get shadow, 
# unless explicitly requested using the wintypes option.
#
# shadow = false;
shadow = true;

# The blur radius for shadows, in pixels. (defaults to 12)
# shadow-radius = 12
shadow-radius = 25;

# The opacity of shadows. (0.0 - 1.0, defaults to 0.75)
shadow-opacity = .50

# The left offset for shadows, in pixels. (defaults to -15)
# shadow-offset-x = -7
shadow-offset-x = -25;

# The top offset for shadows, in pixels. (defaults to -15)
# shadow-offset-y = -15
shadow-offset-y = -25;
# Avoid drawing shadows on dock/panel windows. This option is deprecated,
# you should use the *wintypes* option in your config file instead.
#
dock-shadow = true;

# Don't draw shadows on drag-and-drop windows. This option is deprecated, 
# you should use the *wintypes* option in your config file instead.
#
# no-dnd-shadow = false

# Red color value of shadow (0.0 - 1.0, defaults to 0).
# shadow-red = 0

# Green color value of shadow (0.0 - 1.0, defaults to 0).
# shadow-green = 0

# Blue color value of shadow (0.0 - 1.0, defaults to 0).
# shadow-blue = 0

# Do not paint shadows on shaped windows. Note shaped windows 
# here means windows setting its shape through X Shape extension. 
# Those using ARGB background is beyond our control. 
# Deprecated, use 
#   shadow-exclude = 'bounding_shaped'
# or 
#   shadow-exclude = 'bounding_shaped && !rounded_corners'
# instead.
#
# shadow-ignore-shaped = ''

# Add this one too for ...
    # "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
# Add this one above to the list to have no shadow in Openbox menu
	# "! name~=''",

# Specify a X geometry that describes the region in which shadow should not
# be painted in, such as a dock window region. Use 
#    shadow-exclude-reg = "x10+0+0"
# for example, if the 10 pixels on the bottom of the screen should not have shadows painted on.
#
# shadow-exclude-reg = "" 

# Crop shadow of a window fully on a particular Xinerama screen to the screen.
# xinerama-shadow-crop = false

shadow-exclude = [
  "window_type = 'menu'",
  "class_g = 'Plank'",
  "class_g = 'Cairo-dock'",
  "class_g = 'activate-linux'",
  "class_g = 'firefox'",
  "class_g = 'eww-background-closer'",
  "class_g = 'GLava'",
  "class_g = 'eww-visualizer'",
  "class_g = 'eww-lyrics'",
  "class_g = 'eww-volume-indicator'",
  "class_g = 'eww-brightness-indicator'",
];

#################################
#           Fading              #
#################################


# Fade windows in/out when opening/closing and when opacity changes,
#  unless no-fading-openclose is used.
# fading = false
fading = true;

# Opacity change between steps while fading in. (0.01 - 1.0, defaults to 0.028)
# fade-in-step = 0.028
fade-in-step = 0.03;

# Opacity change between steps while fading out. (0.01 - 1.0, defaults to 0.03)
# fade-out-step = 0.03
fade-out-step = 0.03;

# The time between steps in fade step, in milliseconds. (> 0, defaults to 10)
fade-delta = 4

# Specify a list of conditions of windows that should not be faded.
# fade-exclude = []

# Do not fade on window open/close.
# no-fading-openclose = false

# Do not fade destroyed ARGB windows with WM frame. Workaround of bugs in Openbox, Fluxbox, etc.
# no-fading-destroyed-argb = false


#################################
#   Transparency / Opacity      #
#################################


# Opacity of inactive windows. (0.1 - 1.0, defaults to 1.0)
# inactive-opacity = 1
inactive-opacity = 1.0;

# Opacity of window titlebars and borders. (0.1 - 1.0, disabled by default)
# frame-opacity = 1.0
frame-opacity = 1.0;

# Let inactive opacity set by -i override the '_NET_WM_WINDOW_OPACITY' values of windows.
# inactive-opacity-override = true
inactive-opacity-override = false;

# Default opacity for active windows. (0.0 - 1.0, defaults to 1.0)
# active-opacity = 1.0

# Dim inactive windows. (0.0 - 1.0, defaults to 0.0)
# inactive-dim = 0.0

# Specify a list of conditions of windows that should never be considered focused.
# focus-exclude = []
focus-exclude = [ "class_g = 'Cairo-clock'" ];

# Use fixed inactive dim value, instead of adjusting according to window opacity.
# inactive-dim-fixed = 1.0

# Specify a list of opacity rules, in the format `PERCENT:PATTERN`,
# like `50:name *= "Firefox"`. picom-trans is recommended over this.
# Note we don't make any guarantee about possible conflicts with other
# programs that set '_NET_WM_WINDOW_OPACITY' on frame or client windows.
# example:
#    opacity-rule = [ "80:class_g = 'URxvt'" ];
#
# opacity-rule = []


#################################
#           Corners             #
#################################

# Sets the radius of rounded window corners. When > 0, the compositor will
# round the corners of windows. Does not interact well with
# `transparent-clipping`.
corner-radius = 15

# Exclude conditions for rounded corners.
rounded-corners-exclude = [
  "window_type = 'desktop'",
  "window_type = 'tooltip'",
  "class_g = 'shutter'",
  "class_g = 'eww-*'",
  "class_g = 'activate-linux'",
  "class_g = 'escrotum'",
  "class_g = 'Peek'",
  "class_g = 'firefox'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'Bar'",
  "class_g = 'eww-background-closer'",
#  "class_g = 'GLava'",
];

#################################
#     Background-Blurring       #
#################################


# Parameters for background blurring, see the *BLUR* section for more information.
# blur-method = "dual_kawase"
# blur-size = 12
#
# blur-deviation = true
#
# blur-strength = 5

# Blur background of semi-transparent / ARGB windows.
# Bad in performance, with driver-dependent behavior.
# The name of the switch may change without prior notifications.
#
# blur-background = false

# Blur background of windows when the window frame is not opaque.
# Implies:
#    blur-background
# Bad in performance, with driver-dependent behavior. The name may change.
#
# blur-background-frame = true


# Use fixed blur strength rather than adjusting according to window opacity.
# blur-background-fixed = true


# Specify the blur convolution kernel, with the following format:
# example:
#   blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
#
# blur-kern = ""
# blur-kern = "3x3box";


# Exclude conditions for background blur.
# blur-background-exclude = []
blur-background-exclude = [
  "window_type = 'dock'",
 # "window_type = 'desktop'",
  "window_type = 'menu'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g ~= '^((?!eww-powermenu).)eww-*$'",
  "class_g = 'activate-linux'",
  "class_g = 'escrotum'",
  "class_g = 'Peek'",
  "class_g = 'Tint2'",
  "class_g = 'Slop'",
  "class_g = 'slop'",
  "class_g = 'firefox'",
];

#################################
#       General Settings        #
#################################

# Enable remote control via D-Bus. See the man page for more details.
# dbus = true

# Daemonize process. Fork to background after initialization. Causes issues with certain (badly-written) drivers.
# daemon = false

# Specify the backend to use: `xrender`, `glx`, or `xr_glx_hybrid`.
# `xrender` is the default one.
#
# backend = "glx"
backend = "xrender";

# Enable/disable VSync.
# vsync = false
vsync = true;

# Enable remote control via D-Bus. See the *D-BUS API* section below for more details.
# dbus = false

# Try to detect WM windows (a non-override-redirect window with no
# child that has 'WM_STATE') and mark them as active.
#
# mark-wmwin-focused = false
mark-wmwin-focused = true;

# Mark override-redirect windows that doesn't have a child window with 'WM_STATE' focused.
# mark-ovredir-focused = false
mark-ovredir-focused = true;

# Try to detect windows with rounded corners and don't consider them
# shaped windows. The accuracy is not very high, unfortunately.
#
# detect-rounded-corners = false
detect-rounded-corners = true;

# Detect '_NET_WM_WINDOW_OPACITY' on client windows, useful for window managers
# not passing '_NET_WM_WINDOW_OPACITY' of client windows to frame windows.
#
# detect-client-opacity = false
detect-client-opacity = true;

# Use EWMH '_NET_ACTIVE_WINDOW' to determine currently focused window,
# rather than listening to 'FocusIn'/'FocusOut' event. Might have more accuracy,
# provided that the WM supports it.
#
# use-ewmh-active-win = false

# Unredirect all windows if a full-screen opaque window is detected,
# to maximize performance for full-screen windows. Known to cause flickering
# when redirecting/unredirecting windows.
#
# unredir-if-possible = false

# Delay before unredirecting the window, in milliseconds. Defaults to 0.
# unredir-if-possible-delay = 0

# Conditions of windows that shouldn't be considered full-screen for unredirecting screen.
# unredir-if-possible-exclude = []

# Use 'WM_TRANSIENT_FOR' to group windows, and consider windows
# in the same group focused at the same time.
#
# detect-transient = false
detect-transient = true;

# Use 'WM_CLIENT_LEADER' to group windows, and consider windows in the same
# group focused at the same time. This usually means windows from the same application
# will be considered focused or unfocused at the same time.
# 'WM_TRANSIENT_FOR' has higher priority if detect-transient is enabled, too.
#
# detect-client-leader = false

# Resize damaged region by a specific number of pixels.
# A positive value enlarges it while a negative one shrinks it.
# If the value is positive, those additional pixels will not be actually painted
# to screen, only used in blur calculation, and such. (Due to technical limitations,
# with use-damage, those pixels will still be incorrectly painted to screen.)
# Primarily used to fix the line corruption issues of blur,
# in which case you should use the blur radius value here
# (e.g. with a 3x3 kernel, you should use `--resize-damage 1`,
# with a 5x5 one you use `--resize-damage 2`, and so on).
# May or may not work with *--glx-no-stencil*. Shrinking doesn't function correctly.
#
# resize-damage = 1

# Specify a list of conditions of windows that should be painted with inverted color.
# Resource-hogging, and is not well tested.
#
# invert-color-include = []

# GLX backend: Avoid using stencil buffer, useful if you don't have a stencil buffer.
# Might cause incorrect opacity when rendering transparent content (but never
# practically happened) and may not work with blur-background.
# My tests show a 15% performance boost. Recommended.
#
# glx-no-stencil = false

# GLX backend: Avoid rebinding pixmap on window damage.
# Probably could improve performance on rapid window content changes,
# but is known to break things on some drivers (LLVMpipe, xf86-video-intel, etc.).
# Recommended if it works.
#
# glx-no-rebind-pixmap = false

# Disable the use of damage information.
# This cause the whole screen to be redrawn everytime, instead of the part of the screen
# has actually changed. Potentially degrades the performance, but might fix some artifacts.
# The opposing option is use-damage
#
# no-use-damage = false
use-damage = false;

# Use X Sync fence to sync clients' draw calls, to make sure all draw
# calls are finished before picom starts drawing. Needed on nvidia-drivers
# with GLX backend for some users.
#
# xrender-sync-fence = false

# GLX backend: Use specified GLSL fragment shader for rendering window contents.
# See `compton-default-fshader-win.glsl` and `compton-fake-transparency-fshader-win.glsl`
# in the source tree for examples.
#
# glx-fshader-win = ""

# Force all windows to be painted with blending. Useful if you
# have a glx-fshader-win that could turn opaque pixels transparent.
#
# force-win-blend = false

# Do not use EWMH to detect fullscreen windows.
# Reverts to checking if a window is fullscreen based only on its size and coordinates.
#
# no-ewmh-fullscreen = false

# Dimming bright windows so their brightness doesn't exceed this set value.
# Brightness of a window is estimated by averaging all pixels in the window,
# so this could comes with a performance hit.
# Setting this to 1.0 disables this behaviour. Requires --use-damage to be disabled. (default: 1.0)
#
# max-brightness = 1.0

# Make transparent windows clip other windows like non-transparent windows do,
# instead of blending on top of them.
#
# transparent-clipping = false

# Set the log level. Possible values are:
#  "trace", "debug", "info", "warn", "error"
# in increasing level of importance. Case doesn't matter.
# If using the "TRACE" log level, it's better to log into a file
# using *--log-file*, since it can generate a huge stream of logs.
#
# log-level = "debug"
log-level = "warn";

# Set the log file.
# If *--log-file* is never specified, logs will be written to stderr.
# Otherwise, logs will to written to the given file, though some of the early
# logs might still be written to the stderr.
# When setting this option from the config file, it is recommended to use an absolute path.
#
# log-file = "/path/to/your/log/file"

# Show all X errors (for debugging)
# show-all-xerrors = false

# Write process ID to a file.
# write-pid-path = "/path/to/your/log/file"

# Window type settings
#
# 'WINDOW_TYPE' is one of the 15 window types defined in EWMH standard:
#     "unknown", "desktop", "dock", "toolbar", "menu", "utility",
#     "splash", "dialog", "normal", "dropdown_menu", "popup_menu",
#     "tooltip", "notification", "combo", and "dnd".
#
# Following per window-type options are available: ::
#
#   fade, shadow:::
#     Controls window-type-specific shadow and fade settings.
#
#   opacity:::
#     Controls default opacity of the window type.
#
#   focus:::
#     Controls whether the window of this type is to be always considered focused.
#     (By default, all window types except "normal" and "dialog" has this on.)
#
#   full-shadow=true
#     Controls whether shadow is drawn under the parts of the window that you
#     normally won't be able to see. Useful when the window has parts of it
#     transparent, and you want shadows in those areas.
#
#   clip-shadow-above:::
#     Controls wether shadows that would have been drawn above the window should
#     be clipped. Useful for dock windows that should have no shadow painted on top.
#
#   redir-ignore:::
#     Controls whether this type of windows should cause screen to become
#     redirected again after been unredirected. If you have unredir-if-possible
#     set, and doesn't want certain window to cause unnecessary screen redirection,
#     you can set this to `true`.
#
wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 1.0; focus = true; full-shadow = false; };
  dock = { shadow = true; }
  dnd = { shadow = true; }
  popup_menu = { opacity = 1.0; }
  dropdown_menu = { opacity = 1.0; }
};
```
</details>

### Steps of reproduction
Happens randomly. For example looking at the EasyEffects window quickly increased RAM consumption from 2.7 to 6.3G

**Comment by yshui** [comment] 2022-11-14 15:12
> RAM consumption from 2.7 to 6.3G

You mean the memory consumption of picom?

**Comment by MrIvanPlays** [comment] 2022-11-14 15:14
> > RAM consumption from 2.7 to 6.3G
> 
> You mean the memory consumption of picom?

memory consumption of picom was around 4GB whilst normally it is no more than 2-300MB

**Comment by Monsterovich** [comment] 2022-11-15 12:46
@MrIvanPlays Could you please enable sanitizer in meson_options.txt and rebuild?

Releated issue: https://github.com/yshui/picom/issues/905

**Comment by MrIvanPlays** [comment] 2022-11-15 12:52
905 is not related issue since I did not resize the window.

> Could you please enable sanitizer in meson_options.txt and rebuild?

I have no idea on how to do this. I use `paru` to download stuff from the AUR.

**Comment by Monsterovich** [comment] 2022-11-15 13:31
> 905 is not related issue since I did not resize the window.

It doesn't matter. Memory leaks can be caused by completely different things.

**Comment by Monsterovich** [comment] 2022-11-15 13:56
> I have no idea on how to do this. I use `paru` to download stuff from the AUR.

https://github.com/yshui/picom#to-build

**Comment by passthesh3ll** [comment] 2022-11-18 22:39
I have the same issue
![image](https://user-images.githubusercontent.com/63223659/202814782-7e279336-d07e-4dab-9434-7b134fb1f63d.png)

**Comment by smol-cat** [comment] 2022-11-19 09:30
I have the same issue, memory keeps ramping up when opening and closing windows.

**Comment by SfyMantissa** [comment] 2022-11-19 22:11
I think I am having a similar issue.
I hope this information will be valuable.
Thank you in advance!

### GPU, drivers, and screen setup

One monitor, laptop:

```
sfy@neonblaze: ~ ❱❱ sudo dmidecode -s system-version
ThinkPad X1 Carbon 7th
```

GPU and drivers:

```
sfy@neonblaze: ~ ❱❱ sudo lshw -c video | grep -E 'product|driver'
product: WhiskeyLake-U GT2 [UHD Graphics 620]
configuration: driver=i915 latency=0

sfy@neonblaze: ~ ❱❱ sudo pacman -Q | grep -E 'xf86-video|mesa'
lib32-mesa 22.2.3-1
mesa 22.2.3-1
mesa-utils 8.5.0-2
xf86-video-vesa 2.5.0-3
```

`glxinfo -B` output:

```
sfy@neonblaze: ~ ❱❱ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 620 (WHL GT2) (0x3ea0)
    Version: 22.2.3
    Accelerated: yes
    Video memory: 15677MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.2.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.2.3
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.2.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment

bspwm + sxhkd + picom + polybar + feh + alacritty + rofi

```
sfy@neonblaze: ~ ❱❱ sudo pacman -Q | grep -E '^(bspwm|sxhkd|picom|polybar|feh|alacritty|rofi)'
alacritty 0.11.0-2
bspwm 0.9.10-2
feh 3.9.1-2
picom 10-1
polybar 3.6.3-2
rofi 1.7.5-1
sxhkd 0.6.2-2
```
### picom version

```
sfy@neonblaze: ~ ❱❱ picom --version
vgit-5d150
```
<details>
<summary>Diagnostics</summary>

```
sfy@neonblaze: ~ ❱❱ picom --diagnostics
**Version:** vgit-5d150

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/sfy/.config/picom/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
```
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
sfy@neonblaze: ~ ❱❱ cat .config/picom/picom.conf
#           _
#     ___  (_)______  __ _
#    / _ \/ / __/ _ \/  ' \
#   / .__/_/\__/\___/_/_/_/
#  /_/

#################################
#           Fading              #
#################################

# Fade windows in/out when opening/closing and when opacity changes, # unless no-fading-openclose is used.
fading = true

# Opacity change between steps while fading in. (0.01 - 1.0, defaults to 0.028)
fade-in-step = 0.03;

# Opacity change between steps while fading out. (0.01 - 1.0, defaults to 0.03)
fade-out-step = 0.03;

#################################
#   Transparency / Opacity      #
#################################

# Opacity of inactive windows. (0.1 - 1.0, defaults to 1.0)
inactive-opacity = 0.96;

# Opacity of window titlebars and borders. (0.1 - 1.0, disabled by default)
frame-opacity = 0.7;

# Let inactive opacity set by -i override the '_NET_WM_OPACITY' values of windows.
inactive-opacity-override = true;

# Default opacity for active windows. (0.0 - 1.0, defaults to 1.0)
active-opacity = 0.98;

# Specify a list of opacity rules, in the format `PERCENT:PATTERN`,
# like `50:name *= "Firefox"`. picom-trans is recommended over this.
# Note we don't make any guarantee about possible conflicts with other
# programs that set '_NET_WM_WINDOW_OPACITY' on frame or client windows.

opacity-rule = [
    "100:class_g= 'firefox'",
    "100:class_g= 'Chromium'",
    "100:class_g= 'mpv'",
    "100:class_g= 'telegram-desktop'",
];

#################################
#     Background-Blurring       #
#################################

# Parameters for background blurring, see the *BLUR* section for more information.
# blur-method =
# blur-method = "dual_kawase"
blur-size = 30

# Specify the blur convolution kernel, with the following format:
# example:
#   blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
blur-kern = "11x11gaussian";

# Exclude conditions for background blur.
# blur-background-exclude = []
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

#################################
#       General Settings        #
#################################

# Specify the backend to use: `xrender`, `glx`, or `xr_glx_hybrid`. `xrender` is the default one.
backend = "xrender"
use-damage = "false"

# Enable/disable VSync.
vsync = true

# Try to detect WM windows (a non-override-redirect window with no child that has 'WM_STATE') and mark them as active.
mark-wmwin-focused = true;

# Mark override-redirect windows that doesn't have a child window with 'WM_STATE' focused.
mark-ovredir-focused = false

# Try to detect windows with rounded corners and don't consider them shaped windows. The accuracy is not very high, unfortunately.
detect-rounded-corners = true;

# Detect '_NET_WM_OPACITY' on client windows, useful for window managers not passing '_NET_WM_OPACITY' of client windows to frame windows.
detect-client-opacity = true;

# Use 'WM_TRANSIENT_FOR' to group windows, and consider windows
# in the same group focused at the same time.
#
# detect-transient = false
detect-transient = true

# Use 'WM_CLIENT_LEADER' to group windows, and consider windows in the same
# group focused at the same time. 'WM_TRANSIENT_FOR' has higher priority if
# detect-transient is enabled, too.
#
# detect-client-leader = false
detect-client-leader = true

# Disable the use of damage information.
# This cause the whole screen to be redrawn everytime, instead of the part of the screen
# has actually changed. Potentially degrades the performance, but might fix some artifacts.
# The opposing option is use-damage
use-damage = true

# Set the log level. Possible values are:
#  "trace", "debug", "info", "warn", "error"
# in increasing level of importance. Case doesn't matter.
# If using the "TRACE" log level, it's better to log into a file
# using *--log-file*, since it can generate a huge stream of logs.
log-level = "warn";

# Window type settings
#
# 'WINDOW_TYPE' is one of the 15 window types defined in EWMH standard:
#     "unknown", "desktop", "dock", "toolbar", "menu", "utility",
#     "splash", "dialog", "normal", "dropdown_menu", "popup_menu",
#     "tooltip", "notification", "combo", and "dnd".
#
# Following per window-type options are available: ::
#
#   fade, shadow:::
#     Controls window-type-specific shadow and fade settings.
#
#   opacity:::
#     Controls default opacity of the window type.
#
#   focus:::
#     Controls whether the window of this type is to be always considered focused.
#     (By default, all window types except "normal" and "dialog" has this on.)
#
#   full-shadow:::
#     Controls whether shadow is drawn under the parts of the window that you
#     normally won't be able to see. Useful when the window has parts of it
#     transparent, and you want shadows in those areas.
#
#   redir-ignore:::
#     Controls whether this type of windows should cause screen to become
#     redirected again after been unredirected. If you have unredir-if-possible
#     set, and doesn't want certain window to cause unnecessary screen redirection,
#     you can set this to `true`.
#
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};

corner-radius = 8.0;

rounded-corners-exclude = [
	"class_g = 'polybar'",
	"window_type = 'dock'"
];
```
</details>

### Steps of reproduction

1. Launching picom on startup from my .xinitrc:

```
sfy@neonblaze: ~ ❱❱ cat .xinitrc
#          _      _ __
#   __ __ (_)__  (_) /_________
#   \ \ // / _ \/ / __/ __/ __/
#  /_\_\/_/_//_/_/\__/_/  \__/
#

eval $(ssh-agent)
setxkbmap -option compose:ralt
setxkbmap -layout us,ru -option grp:win_space_toggle
picom &
~/.fehbg
exec dbus-launch bspwm
```

2. picom is "alive" (note memory consumption).

```
sfy@neonblaze: ~ ❱❱ ps auxf | grep sfy.*picom | grep -v grep
sfy         5922  0.4  0.0  15704  6752 pts/1    S    02:56   0:00      \_ picom

sfy@neonblaze: ~ ❱❱ date; free -h
Sun 20 Nov 2022 02:58:31 +06
               total        used        free      shared  buff/cache   available
Mem:            15Gi       3,1Gi       4,9Gi       5,7Gi       7,3Gi       6,2Gi
Swap:          2,0Gi          0B       2,0Gi

sfy@neonblaze: ~ ❱❱ date; free -h
Sun 20 Nov 2022 02:59:31 +06
               total        used        free      shared  buff/cache   available
Mem:            15Gi       3,0Gi       4,0Gi       6,7Gi       8,3Gi       5,2Gi
Swap:          2,0Gi          0B       2,0Gi
```

3. picom is "killed".
No changes to other processes running on the system.

```
sfy@neonblaze: ~ ❱❱ ps auxf | grep sfy.*picom | grep -v grep | wc -l
0

sfy@neonblaze: ~ ❱❱ date; free -h
Sun 20 Nov 2022 03:00:41 +06
               total        used        free      shared  buff/cache   available
Mem:            15Gi       3,1Gi        10Gi       272Mi       1,8Gi        11Gi
Swap:          2,0Gi          0B       2,0Gi

sfy@neonblaze: ~ ❱❱ date; free -h
Sun 20 Nov 2022 03:01:41 +06
               total        used        free      shared  buff/cache   available
Mem:            15Gi       3,1Gi        10Gi       278Mi       1,8Gi        11Gi
Swap:          2,0Gi          0B       2,0Gi
```

4. Memory leak started after upgrading picom.

```
sfy@neonblaze: ~ ❱❱ grep 2022-11-19.*picom /var/log/pacman.log
[2022-11-19T15:58:15+0600] [ALPM] upgraded picom (9.1-3 -> 10-1)
```

### Expected behavior

No memory leak.

### Current Behavior

Memory leak.

**Comment by Monsterovich** [comment] 2022-11-20 00:41
@SfyMantissa I have similar iGPU on my laptop, but no memory leaks. I thought this is NVidia-only issue.

```
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 520 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.2.3 - kisak-mesa PPA
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.2.3 - kisak-mesa PPA
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
```

**Comment by yshui** [comment] 2022-11-20 18:56
Duplicate of #892

**Closed as completed by yshui** 2022-11-20 18:56 UTC
