### ISSUE TITLE
Windows redrawing problems with glx and software rendering (llvmpipe)

### ISSUE THREAD

**Issue by XoDefender** [yshui/compton#1218] opened 2024-03-11 07:38 UTC
### GPU, drivers, and screen setup
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 15.0.6, 256 bits) (0xffffffff)
    Version: 22.3.6
    Accelerated: no
    Video memory: 4762MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 15.0.6, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.3.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.3.6
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### picom version
v10.2

### Configuration:
<details>
    <summary>Configuration file</summary>

```
shadow = true;
shadow-active = true;
shadow-radius = 10;
shadow-opacity = 0.2;
shadow-offset-x = -10;
shadow-offset-y = -7;
fading = false;
fade-in-step = 0.03;
fade-out-step = 0.03;
enable-transparency = false;
inactive-opacity = 1.0;
inactive-opacity-override = false;
focus-exclude = [ "class_g = 'Cairo-clock'" ];
opacity-rule = [ "0:_NET_WM_STATE@[0]:32a *= '_NET_WM_STATE_HIDDEN'", "0:_NET_WM_STATE@[1]:32a *= '_NET_WM_STATE_HIDDEN'", "0:_NET_WM_STATE@[2]:32a *= '_NET_WM_STATE_HIDDEN'", "0:_NET_WM_STATE@[3]:32a *= '_NET_WM_STATE_HIDDEN'", "0:_NET_WM_STATE@[4]:32a *= '_NET_WM_STATE_HIDDEN'" ];
corner-radius = 7;
rounded-corners-exclude = [ "window_type = 'dock'", "window_type = 'desktop'", "class_g ?= 'Firefox'" ];
blur-kern = "3x3box";
blur-background-exclude = [ "window_type = 'dock'", "window_type = 'desktop'", "class_g = 'firefox' && (window_type = 'popup_menu' || window_type = 'utility')", "_GTK_FRAME_EXTENTS@:c" ];
backend = "glx";
vsync = false;
dbus = false;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-ewmh-active-win = true;
unredir-if-possible = true;
detect-transient = true;
detect-client-leader = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;
xrender-sync-fence = false;
no-ewmh-fullscreen = false;
log-level = "warn";
frame-opacity = 1.0;
```
</details>

### Steps of reproduction
1. Start picom with glx backend on a virtual machine with the llvmpipe driver or with LIBGL_ALWAYS_SOFTWARE=1on a physical device
2. Hide and show a window or open a window which content dynamically changes 

### Expected behavior
the window redraws properly

### Current Behavior
the window stops redrawing, the content updates (redraws) after window resizing

### Other details
I understand that the problem is with software rendering, but it would be cool to run picom with glx and get rid of some xrender bugs even with such driver as llvmpipe. Probably, there is a way around. I will also investigate this problem by myself, so it would be great to hear any guesses, how it could be fixed)
![изображение](https://github.com/yshui/picom/assets/90552397/06871d99-3f79-44ff-9cb1-356804aa1f0d)

**Comment by ivanp7** [comment] 2024-03-25 14:50
Can confirm, I experience the same issue with llvmpipe+glx on picom v11.2

**Comment by XoDefender** [comment] 2024-04-02 09:29
It works fine with the legacy **glx** backend and **glx-no-rebind-pixmap = false;**

**Comment by absolutelynothelix** [comment] 2024-10-21 08:21
closing as duplicate of #1030.

**Closed as not planned by absolutelynothelix** 2024-10-21 08:21 UTC
Labels: duplicate
