### ISSUE TITLE
picom: symbol lookup error: picom: undefined symbol: eglCreateImage

### ISSUE THREAD

**Issue by HCh-AP** [yshui/compton#961] opened 2022-12-06 13:02 UTC
After update to  picom 10.1-1 quits with this error message. 

"picom: symbol lookup error: picom: undefined symbol: eglCreateImage"

### Platform

Manjaro 22.0.0

### GPU, drivers, and screen setup

Nvidia-340 proprietary drivers 

### Environment

XFCE 

### picom version

10.1-1

### Configuration:

backend = "glx";
no-use-damage = false;
vsync = true;
unredir-if-possible = false;
xrender-sync-fence = true;
detect-rounded-corners = false;
no-dock-shadow = false;
no-dnd-shadow = true;
shadow-exclude = [ "n:e:Notification", 
                                "n:e:Docky",
                                "g:e:Synapse",
                                "g:e:Conky",
                                "n:w:*dockbarx*",
                                "name = 'firefox.real' ",
                                "class_g ?= 'Cairo-dock'",
                                "class_g ?= 'VirtualBoxVM'",
                                "class_g ?= 'VirtualBox'",
                                "class_g ?= 'Xfce4-notifyd'",
                                "class_g ?= 'xfce4-notifyd'",
                                "class_g ?= 'Xfce4-power-manager'",
                                "class_g ?= 'Notify-osd'",
                                "class_g ?= 'vlc'",
                                "_GTK_FRAME_EXTENTS@:c",
                                "class_g = 'firefox' && argb",
                                "class_g = 'firefox.real' && argb"];
fading = false;
detect-client-opacity = true;
wintypes :
{
        tooltip :   {    shadow = true;   };
        menu :     {    shadow = true;   };
        desktop :     {    shadow = true;   };
        normal :  {    shadow = true;    };
        unknown :  {    shadow = true;    };
        dock :   {    shadow = true;    };
        toolbar :  {    shadow = true;    };
        utility :  {    shadow = true;    };
        splash :   {    shadow = true;    };
        dialog :   {    shadow = true;    };
        dropdown_menu :   {    shadow = false;    };
        popup_menu :  {    shadow = false;    };
        notification :   {    shadow = true;    };
        combo :  {    shadow = true;    };
        dnd :   {    shadow = true;    };
};
use-ewmh-active-win = true;
no-ewmh-fullscreen = false;

### Steps of reproduction

Just run picom from command line. 

#>picom
#>picom: symbol lookup error: picom: undefined symbol: eglCreateImage
#>

### Current Behavior
picom exits with this error message: 

"picom: symbol lookup error: picom: undefined symbol: eglCreateImage"

**Comment by yshui** [comment] 2022-12-06 14:06
duplicate of #945

**Closed as completed by yshui** 2022-12-06 14:06 UTC
