### ISSUE TITLE
Regarding shadows in xrender backend and new bug

### ISSUE THREAD

**Issue by gh0stzk** [yshui/compton#1358] opened 2024-10-13 03:30 UTC
Regarding the issue https://github.com/yshui/picom/issues/1352 now is fixed but a line above and sometimes under the window is painted.

### Platform
Arch, bspwm wm.

### Configuration:
<details>
    <summary>Configuration file</summary>

```
## ----- Shadows ----- ##

shadow = true;

shadow-radius = 7;
#shadow-opacity = .6
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-color = "#FF0000"

## ----- Fading ----- ##

fading = true;

fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5
no-fading-openclose = true
no-fading-destroyed-argb = true

## ----- Transparency ----- ##

frame-opacity = 1.0;

# inactive-dim-fixed = true

## ----- Corners ----- ##

corner-radius = 6

#################################
#       General Settings        #
#################################

# Available backends "xrender" "glx" "egl"
backend = "xrender"

dithered-present = false;
vsync = true;

detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;

use-damage = true;
# xrender-sync-fence = false
# transparent-clipping = false
```
</details>

### Steps of reproduction
at start and no matter if i kill picom and restart it again

![Shot-2024-10-12-212823](https://github.com/user-attachments/assets/31ac6e80-b68e-49e0-9bad-66eb3c5b7864)

**Comment by yshui** [comment] 2024-10-13 09:19
do you have an intel igpu?

**Comment by yshui** [comment] 2024-10-13 09:40
hmm, can't reproduce it here

**Comment by gh0stzk** [comment] 2024-10-13 12:55
> do you have an intel igpu?

oww sorry for that, I forgot to specify and clarify, on amd the problem does not exist, the problem mentioned above is with intel with an igpu with the xf86-video-intel driver

**Comment by absolutelynothelix** [comment] 2024-10-13 13:30
> the xf86-video-intel driver

pure evil

**Comment by absolutelynothelix** [comment] 2024-10-21 07:13
does the issue happen without the `xf86-video-intel` package installed?

**Comment by absolutelynothelix** [comment] 2024-11-06 08:31
closing as duplicate of #1349.

**Closed as not planned by absolutelynothelix** 2024-11-06 08:31 UTC
Labels: duplicate
