### ISSUE TITLE
Feature Request: Allow corner-radius setting to specify separate corner rounding

### ISSUE THREAD

**Issue by efylan** [yshui/compton#946] opened 2022-11-28 06:52 UTC
And have something like 

`
corner-radius=["top-left=0","top-right=0", "bottom-left=4", "bottom-right=4"] 
`

and/or

`
corner-radius=["top=0", "bottom=4"] 
`

In addition to the way that it's specified presently.

**Comment by yshui** [comment] 2022-11-28 10:19
Duplicate of #918

**Closed as completed** 2022-11-28 10:20 UTC
