### ISSUE TITLE
black window while closing animation in openbox

### ISSUE THREAD

**Issue by Dumbrusher** [yshui/compton#1356] opened 2024-10-11 20:50 UTC
### Platform

Arch

### GPU, drivers, and screen setup

Intel UHD,mesa 1:24.2.4-1 and NVidia RTX 3050, nvidia-drivers 560.35.03-258, single monitor

### Environment

Desktop Environment: xfce4, Window Manager: openbox

### picom version

v12.2 (/startdir/picom revision f9f6f2c)
<details>
<summary>Diagnostics</summary>

**Version:** v12.2 (/startdir/picom revision f9f6f2c)

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file specified: None
* Config file used: /home/aakash/.config/picom.conf

### Drivers (inaccurate):

NVIDIA, modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) Graphics (RPL-S)
* Accelerated: 1
[ 10/12/2024 01:52:12.831 egl_init WARN ] The egl backend is still experimental, use with care.

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) Graphics (RPL-S)

</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
shadow = true;
shadow-radius = 30;
shadow-opacity = 1
shadow-offset-x = -30;
shadow-offset-y = -30;
shadow-color = "#00020b"

frame-opacity = 0.95;
frame-opacity-for-same-colors = true;

corner-radius = 0

blur-method = "dual_kawase"
blur-background = true
blur-background-frame = true
fade = true
backend = "glx"
dithered-present = false;
vsync = true;
detect-client-opacity = true;
detect-transient = true;
detect-client-leader = true
glx-no-stencil = true
glx-no-rebind-pixmap = true
use-damage = true;
xrender-sync-fence = true
log-level = "warn";
# no-fading-destroyed-argb = true

rules = (
    {
        match = "class_i = 'fdesktop'";
        animations = ({
            triggers = ["open","show"];
            offset-x = {
                start = 1000;
                end = 0;
                duration = 1;
            }
        })
    },
    {
        match = "_NET_FRAME_EXTENT@ = 1";
        animations = (
            {
                triggers = ["hide"];
                preset = "fly-in";
                direction = "left";
                duration = "1"
            }
        )
    },
    {
        match = "class_g = 'Deadd-notification-center'";
        animations = (
            {
            triggers = ["open", "show"];
            preset = "slide-in";
            direction = "right";
            duration = "0.5"
            },
            {
                triggers = ["close", "hide"];
                preset = "slide-out";
                direction = "right";
                duration = "0.5"
            }
        )
    },
    {
    match = "WM_TRANSIENT_FOR@";
    animations = ({
        triggers = ["open", "show"];
        opacity = {
            curve = "linear";
            duration = 0.15;
            start = "window-raw-opacity-before";
            end = "window-raw-opacity";
        };
        blur-opacity = {
            curve = "linear";
            duration = 0.1;
            delay = 0.15;
            start = "window-raw-opacity-before";
            end = "window-raw-opacity";
        };
        shadow-opacity = "opacity";
        scale-y = {
            curve = "cubic-bezier(0.24, 0.64, 0.79, 0.98)";
            duration = 0.15;
            start = 0.8;
            end = 1;
        };
        offset-y = "(-window-height/2) + (window-height/2) * scale-y";
        shadow-scale-y = "scale-y";
        shadow-offset-y = "offset-y";
    },{
        triggers = ["close", "hide"];
        opacity = {
            curve = "linear";
            duration = 0.15;
            start = "window-raw-opacity-before";
            end = "0";
        };
        blur-opacity = 0;
        shadow-opacity = "opacity";
        scale-y = {
            curve = "cubic-bezier(0.21, 0.02, 0.76, 0.36)";
            duration = 0.15;
            start = 1;
            end = 0.7;
        };
        offset-y = "(-window-height/2) + (window-height/2) * scale-y";
        shadow-scale-y = "scale-y";
        shadow-offset-y = "offset-y";
    });
}, {
    match = "window_type = 'dropdown_menu' || window_type = 'popup_menu' || window_type = 'menu'";
    animations = ({
        triggers = ["open", "show"];
        opacity = {
            curve = "linear";
            duration = 0.15;
            start = "window-raw-opacity-before";
            end = "window-raw-opacity";
        };
        blur-opacity = {
            curve = "linear";
            duration = 0.1;
            delay = 0.15;
            start = "window-raw-opacity-before";
            end = "window-raw-opacity";
        };
        shadow-opacity = "opacity";
        scale-y = {
            curve = "cubic-bezier(0.24, 0.64, 0.79, 0.98)";
            duration = 0.15;
            start = 0.8;
            end = 1;
        };
        shadow-scale-y = "scale-y";
    },{
        triggers = ["close", "hide"];
        opacity = {
            curve = "linear";
            duration = 0.15;
            start = "window-raw-opacity-before";
            end = "0";
        };
        blur-opacity = 0;
        shadow-opacity = "opacity";
        scale-y = {
            curve = "cubic-bezier(0.21, 0.02, 0.76, 0.36)";
            duration = 0.15;
            start = 1;
            end = 0.7;
        };
        shadow-scale-y = "scale-y";
    });
}, {
    match = "window_type = 'dropdown_menu' || window_type = 'popup_menu' || window_type = 'menu'";
    opacity = 0.9;
}, {
    match = "window_type = 'dock' || window_type = 'desktop'";
    blur-background = false;
    corner-radius = 0;
}, {
    match = "class_g *= 'i3lock' || _NET_WM_STATE@[1] = '_NET_WM_STATE_FULLSCREEN' || _NET_WM_STATE@[2] = '_NET_WM_STATE_FULLSCREEN' || _NET_WM_STATE@[3] = '_NET_WM_STATE_FULLSCREEN' || _NET_WM_STATE@[4] = '_NET_WM_STATE_FULLSCREEN'";
    shadow = false;
    corner-radius = 0;
    animations = ({
        triggers = ["open", "show"];
        opacity = {
            curve = "linear";
            duration = 0.15;
            start = "window-raw-opacity-before";
            end = "window-raw-opacity";
        };
        blur-opacity = {
            curve = "linear";
            duration = 0.1;
            delay = 0.15;
            start = "window-raw-opacity-before";
            end = "window-raw-opacity";
        };
        shadow-opacity = "opacity";
    },{
        triggers = ["close", "hide"];
        opacity = {
            curve = "linear";
            duration = 0.15;
            start = "window-raw-opacity-before";
            end = "0";
        };
        blur-opacity = 0;
        shadow-opacity = "opacity";
    });
});

animations = ({
    triggers = ["close", "hide"];
    opacity = {
        curve = "linear";
        duration = 3;
        start = "window-raw-opacity-before";
        end = "window-raw-opacity-before";
    };
    blur-opacity = "0";
    shadow-opacity = "opacity";
    offset-x = "(1 - scale-x) / 2 * window-width";
    offset-y = "(1 - scale-y) / 2 * window-height * 5";
    scale-x = {
        curve = "cubic-bezier(0.21, 0.02, 0.76, 0.36)";
        duration = 1;
        start = 1;
        end = 0.9;
    };
    scale-y = "scale-x";
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
}, {
    triggers = ["open", "show"];
    opacity = {
        curve = "linear";
        duration = 0.15;
        start = "window-raw-opacity-before";
        end = "window-raw-opacity";
    };
    blur-opacity = {
        curve = "linear";
        duration = 0.1;
        delay = 0.15;
        start = "window-raw-opacity-before";
        end = "window-raw-opacity";
    };
    shadow-opacity = "opacity";
    offset-x = "(1 - scale-x) / 2 * window-width";
    offset-y = "(1 - scale-y) / 2 * window-height * 5";
    scale-x = {
        curve = "cubic-bezier(0.24, 0.64, 0.79, 0.98)";
        duration = 0.15;
        start = 0.95;
        end = 1;
    };
    scale-y = "scale-x";
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
}

)
```
</details>

### Steps of reproduction

1.Closing a window 
2.

### Expected behavior
closing animation should not turn window black
### Current Behavior
whenever i close a window its content becomes black and animations goes on 
### OpenGL trace

i dont know what to do with picom.trace file so here is the link https://drive.google.com/file/d/1pb4Bi4XuMDq8JvHQCc7g5anHkKjEhCCH/view?usp=sharing

### Other details

https://drive.google.com/file/d/1r5ZLF3FdELfV5RXA0Sej5jr-YK_suUqz/view?usp=sharing
in xfwm4 same thing happes but windows contents are transparent instead of black

**Comment by absolutelynothelix** [comment] 2024-10-11 21:06
the xfwm4 issue is upstream so the openbox one i believe.

**Comment by Dumbrusher** [comment] 2024-10-11 21:18
i guess i have to minimize and close every window 😅

**Comment by absolutelynothelix** [comment] 2024-10-21 07:42
> the xfwm4 issue is upstream so the openbox one i believe.

the xfwm4 issue is caused by xfwm4 destroying the window before it's frame and is [reported upstream](https://gitlab.xfce.org/xfce/xfwm4/-/issues/766). i don't know about the openbox one but given that we have the `--no-fading-destroyed-argb` option (see it's description in the manual) i believe that the situation there is similar.

we prefer to have these issues fixed upstream as the only possible workaround on our side will have a performance impact.

closing as wontfix.

**Closed as not planned by absolutelynothelix** 2024-10-21 07:42 UTC
Labels: wontfix, upstream
