### ISSUE TITLE
Suggestion: Hide desktop entries under Wayland

### ISSUE THREAD

**Issue by LRitzdorf** [yshui/compton#1100] opened 2023-07-20 18:46 UTC
### Platform
Arch Linux (standard 64-bit)

### Context
For the past while, I have used i3 with picom, and been generally happy with that setup. However, I'm interested in trying out this newfangled Wayland thing, and to that end have installed Hyprland. Configuring it, and working with autostart functionality in particular, led me to the observation below.

### Suggestion
Currently, picom installs a desktop file to facilitate its startup, both as a standard application and an XDG autostart entry. While helpful under X11, both entry types remain active when in a Wayland environment. This is particularly annoying for the autostart entry, since it is clearly not needed when a Wayland compositor is already active. **If feasible, the ability to hide both entries under Wayland would be greatly appreciated.**

We're obviously somewhat limited by the constraints of the XDG Desktop Entry spec here. Based on some quick research, it seems that while there's no way to detect a Wayland environment *directly* as such, we might be able to use the `NotShowIn` or `OnlyShowIn` keys to similar effect. The downside here is that we'd need to maintain a blacklist or whitelist of DEs and WMs where picom should/can be autostarted, which might be a bit clunky.

If anyone else is aware of a cleaner solution, please let me know! I'd also be happy to PR whatever we come up with.

For ease of referencing: https://wiki.archlinux.org/title/desktop_entries#Hide_desktop_entries

**Comment by absolutelynothelix** [comment] 2024-10-21 09:19
closing as duplicate of #1276.

**Closed as not planned by absolutelynothelix** 2024-10-21 09:19 UTC
Labels: duplicate
