### ISSUE TITLE
C library ev not found (libev doesn't provide a .pc for pkg-config)

### ISSUE THREAD

**Issue by jocap** [yshui/compton#113] opened 2019-02-12 22:11 UTC
### Platform
OpenBSD 6.4

### Compton version
5.1

### Problem
When building:

    meson --buildtype=release . build

... the library 'ev' is not found, even though I have libev installed.

I guess this is because libev doesn't provide a .pc file for pkg-config, which I presume meson tries to use to find it. While some GNU/Linux distributions provide their own .pc for libev, I don't think that the maintainers of libev do. The OpenBSD doesn't provide its own .pc.

I'm not familiar enough with meson to fix this, but it must be possible to supply a path manually instead of using pkg-config.

**Comment by remyabel** [comment] 2019-02-13 01:40
The problem isn't the lack of a `pc` file. In this instance, meson will do a test compile (similar to the autotools feature):

```
Command line:  cc /tmp/tmprtq_czqi/testfile.c -pipe -D_FILE_OFFSET_BITS=64 -o /tmp/tmprtq_czqi/output.exe -O0 -Wl,--start-group -lev -Wl,--end-group -Wl,--allow-shlib-undefined

Code:
 int main(int argc, char **argv) { return 0; }
Compiler stdout:

Compiler stderr:

Library ev found: YES
```

More than likely you are missing `libev-devel`.

**Comment by remyabel** [comment] 2019-02-13 01:58
Actually, I think this might be a bug in Meson. See [#3570](https://github.com/mesonbuild/meson/issues/3570).

**Comment by yshui** [comment] 2019-02-13 02:07
/me starts to think whether using meson is really a good idea or not :/

**Comment by apetresc** [comment] 2019-04-24 01:50
I think I might be experiencing the same problem on Ubuntu 19.04. I have both `libev4` and `libev-dev` installed, but `meson --buildtype=release . build`  still prints:

```
|Subproject test.h finished.
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Found CMake: /usr/bin/cmake (3.13.4)
Dependency libev found: NO (tried pkgconfig and cmake)
Library ev found: YES
Library m found: YES
Dependency xcb found: YES 1.13.1
Dependency x11 found: YES 1.6.7
Dependency x11-xcb found: YES 1.6.7
Dependency xcb-renderutil found: YES 0.3.9
Dependency xcb-render found: YES 1.13.1
Dependency xcb-damage found: YES 1.13.1
Dependency xcb-randr found: YES 1.13.1
Dependency xcb-sync found: YES 1.13.1
Dependency xcb-composite found: YES 1.13.1
Dependency xcb-shape found: YES 1.13.1
Dependency xcb-image found: YES 0.4.0
Dependency xcb-xinerama found: YES 1.13.1
Dependency xcb-xfixes found: YES 1.13.1
Dependency xcb-present found: YES 1.13.1
Dependency xext found: YES 1.3.3
Dependency pixman-1 found: YES 0.36.0
Has header "uthash.h" : YES
Dependency libconfig found: YES 1.5
Dependency libxdg-basedir found: YES 1.2.0
Dependency libpcre found: YES 8.39
Dependency gl found: YES 19.0.2
Dependency dbus-1 found: YES 1.12.12
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja
```
The build still works fine but that `Dependency libev found: NO (tried pkgconfig and cmake)` is upsetting. Should I just be ignoring it?

**Comment by yshui** [comment] 2019-04-24 09:24
@apetresc Yes, you should

**Comment by yshui** [comment] 2019-04-27 13:36
@jocap Please refer to https://github.com/yshui/compton#to-build on what you might need to do to help meson find libev, it has been updated.

Closing.

**Closed by yshui** 2019-04-27 13:36 UTC
Labels: upstream

**Comment by galou** [comment] 2021-03-11 15:07
https://github.com/yshui/compton#to-build actually links to https://github.com/yshui/picom#to-build. Is it intended?

I have the same issue on Ubuntu 20.04.

I tried using `LDFLAGS`:
```
LDFLAGS="-L/usr/lib/x86_64-linux-gnu" meson --buildtype=release . build
```
but it didn't help, thought the files `libev.so` and `libev.a` are in `/usr/lib/x86_64-linux-gnu`.

**Comment by AnabelBerumen** [comment] 2022-08-21 10:22
sudo apt-get install libev-dev

**Comment by omen-works** [comment] 2023-03-02 22:47
Running into the same problem on Ubuntu 22.04.2 LTS

Run-time dependency libev found: NO (tried pkgconfig and cmake)
Run-time dependency x11 found: NO (tried pkgconfig and cmake)
src/meson.build:27:1: ERROR: Dependency "x11" not found, tried pkgconfig and cmake

**Comment by tryone144** [comment] 2023-03-02 23:24
The libev not found isn't critical. 

> ERROR: Dependency "x11" not found, tried pkgconfig and cmake

This however is a problem. Are you sure you have the x11 development packages installed? [README](https://github.com/yshui/picom#dependencies)

**Comment by omen-works** [comment] 2023-03-04 20:07
Unfortunately yes. I have installed all the requirements. Any ideas what else I could try?

**Comment by jackiesogi** [comment] 2023-12-18 18:55
Same issue of "Run-time dependency libev found: NO"
Tried so hard on Ubuntu 22.04 and Kali 2023.4, neither one worked :(

**Comment by absolutelynothelix** [comment] 2023-12-19 21:09
@jackiesogi, if your build log looks like this:
```
Run-time dependency libev found: NO (tried pkgconfig and cmake)
Library ev found: YES
```

then it's fine, the message above is harmless.

**Comment by jackiesogi** [comment] 2023-12-24 08:08
@absolutelynothelix OK! Thanks for your reply!
