### ISSUE TITLE
Blur casts a shadow over i3 title bar and windows on other monitors

### ISSUE THREAD

**Issue by lillemets** [yshui/compton#1165] opened 2024-01-24 10:05 UTC
### Platform

Arch Linux, Linux 6.7.0-arch3-1

### GPU, drivers, and screen setup

AMD Ryzen 7 5700G with Radeon Graphics, two monitors configured side-by-side with xrandr

### Environment

i3wm

### picom version

vgit-197b4
<details>
<summary>Diagnostics</summary>

```
**Version:** vgit-197b4

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/jrl/.config/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: AMD
* GL renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 16.0.6, DRM 3.56, 6.7.0-arch3-1)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: radeonsi
 * GL: AMD
* GL renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 16.0.6, DRM 3.56, 6.7.0-arch3-1)
* ```
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
# Shadow
shadow = true;
shadow-radius = 20;
shadow-opacity = 0.5;
shadow-offset-x = -20;
shadow-offset-y = -20;
crop-shadow-to-monitor = true;
shadow-exclude = [
  "class_g = 'i3-frame'",
  ];

# Fading
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 5;
fade-exclude = [];

# Corners
corner-radius = 15;
rounded-corners-exclude = [
  "class_g = 'i3-frame'",
  ];

# Blur
blur-method = "dual_kawase";
blur-kern = "3x3box";
blur-strength = 5;
blur-background-exclude = [
];

# Other
backend = "glx";
#vsync = true; # Avoid tearing
detect-rounded-corners = true;
wintypes:
{
  menu          = { opacity = 0.8; };
  utility       = { opacity = 0.8; };
  dropdown_menu = { opacity = 0.8; };
  popup_menu    = { opacity = 0.8; };
  tooltip       = { opacity = 0.8; };
}
```
</details>

### Expected behavior

The blur effect is restricted to window borders and does not cast a white shadow over other windows and monitors.

### Current Behavior

When using `dual_kawase` blur, light colored windows cast a white shadow over a dark i3 title bar. This shadow is also cast over windows on adjacent monitors. It is visible only if a window on that other monitor is dark. Not only is this aesthetically unpleasant but it also makes reading text on title bars more difficult.

![240124120325](https://github.com/yshui/picom/assets/16861099/1d518758-5580-4c0a-8bcc-b0e7ff2f752a)

As can be seen above, the white shadow does not appear over Polybar.

The shadow does not appear with other blur methods such as the `gaussian` blur. But the other blur methods barely create any blur effect and are practically useless.

![240124120308](https://github.com/yshui/picom/assets/16861099/477e2e08-372d-47f0-a853-4efe4f93d991)

I never had this issue with the [bhagwan/picom-ibhagwan-git](https://github.com/ibhagwan/picom-ibhagwan-git) fork, but that unfortunately has dissappeared from the internet.

**Comment by absolutelynothelix** [comment] 2024-01-24 10:14
possibly a duplicate of #854.

**Comment by yshui** [comment] 2024-01-25 03:59
duplicate of #854 

arguably the intended behavior

**Closed as not planned by yshui** 2024-01-25 03:59 UTC

**Comment by ironhak** [comment] 2025-08-09 13:36
A bit late, but this solves it:
```
rules = (
    {
        match = "( class_g = 'i3-frame' || "
                "class_g = 'i3bar' )";
        shadow = false;
        blur-background = false
    },
)
```
