### ISSUE TITLE
vsync issues since v6

### ISSUE THREAD

**Issue by adithyabhatkajake** [yshui/compton#180] opened 2019-05-26 01:10 UTC
### Platform
Arch Linux, 64 bit

### GPU, drivers, and screen setup
Nvidia GTX 1050Ti, nvidia 430.14-3, xf86-video-intel 1:2.99.917+863+g6afed33b-1, mesa 19.0.4-1

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)  (0x3e9b)
    Version: 19.0.4
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.4
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.0.4
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Environment
i3-gaps

### Compton version
v6.2, 
**Version:** v6.2

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/haxolotl/.config/compton.conf

### Compton configuration:
```
backend = "glx";
glx-swap-method = 1;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;
shadow = true;
shadow-radius = 5;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.5;

shadow-exclude = [
    "! name~=''",
    "name = 'Notification'",
    "name = 'Plank'",
    "name *= 'VLC'",
    "name *= 'compton'",
    "name *= 'Chromium'",
    "name *= 'Chrome'",
    "class_g = 'Firefox' && argb",
    "class_g = 'Synapse'",
    "class_g ?= 'Notify-osd'",
    "_GTK_FRAME_EXTENTS@:c",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];
shadow-ignore-shaped = false;

inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;

inactive-dim = 0.2;
blur-background = true;
blur-background-fixed = false;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

fading = true;
fade-delta = 15;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ 
];
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = true;
dbe = true;

focused.
focus-exclude = [
    "class_g = 'Evince'",
];

detect-transient = true;
detect-client-leader = true;

wintypes:
{
    tooltip =
    {
        fade = true;
        shadow = false;
        opacity = 0.85;
        focus = true;
    };
    dock = 
    { 
        shadow = false; 
    };
    popup_menu = 
    { 
        opacity = 1 
    };
    dropdown_menu = 
    { 
        opacity = 1 
    };
    dnd = 
    { 
        shadow = false; 
    };
};
xrender-sync-fence = true;

```

### Steps of reproduction

1. Run compton without any configuration
2. Start `urxvt`
3. Press enter on urxvt and lines start appearing

### Expected behavior
No lines

### Current Behavior
Lines in urxvt

https://imgur.com/gallery/lR49QP6
Screenshot, if it helps.

**Comment by yshui** [comment] 2019-05-26 14:05
> Press enter on urxvt and lines start appearing

what does this mean?

**Comment by adithyabhatkajake** [comment] 2019-05-26 19:49
These lines appear whenever the terminal refreshes the content, for example in vim, less, tmux or by simply pressing enter in the terminal (middle terminal in the screenshot).

**Comment by yshui** [comment] 2019-05-27 21:33
@adithyabhatkajake How is that a performance problem?

**Comment by adithyabhatkajake** [comment] 2019-05-28 15:01
I changed the title. My bad.

**Comment by yshui** [comment] 2019-06-01 16:52
Does those lines go away if you disable `blur-background`?

**Comment by morgoth6** [comment] 2019-06-02 10:17
Try with use-damage = false; I had no time to investigate, but this solve Urxvt redraw/refresh problem here.

**Comment by adithyabhatkajake** [comment] 2019-06-02 19:28
Setting `blur-background = false;` or `use-damage = false;` fixes the Urxvt problem.

**Comment by yshui** [comment] 2019-06-03 08:33
So this is a duplicate of #50 then

**Closed** 2019-06-03 08:34 UTC
