### ISSUE TITLE
Enabling shadows on xrender slows down picom

### ISSUE THREAD

**Issue by siduck** [yshui/compton#1351] opened 2024-10-10 13:17 UTC
Hi, just got to know that picom finally supports animations, after trying it it asked me to specify backend in the config

I added glx  and then the ram usage got high, upto 170 mb

![image](https://github.com/user-attachments/assets/929df1fb-00ce-41d0-a852-010bb28801e2)

I was using picom-ftlabs-git on aur before, animations work great there + dont have to use glx and it barely takes 10mb!

https://github.com/user-attachments/assets/fef14811-8dee-4784-afb3-68237e921f48

**Comment by yshui** [comment] 2024-10-10 14:34
170mb memory usage can hardly be considered high (you have 30GB! 170mb is only 0.6%). and you don't have to use glx if you don't want to, animation works on xrender.

**Comment by siduck** [comment] 2024-10-10 14:47
> 170mb memory usage can hardly be considered high (you have 30GB! 170mb is only 0.6%).

I get nice animations and all, on picom-ftlabs-git package previous picom forks with animations in just 10 mb! which is so cool but i feel like the the new picom has increased ram usage

Xrender feels so laggy when enabling shadows 
 

https://github.com/user-attachments/assets/11141826-ebcb-4b8e-a5a8-2b7120e78859

**Comment by yshui** [comment] 2024-10-10 15:02
> in just 10 mb!

does picom-ftlabs still use 10 mb on glx? glx do use more memory but that's mostly from the gl driver. and i personally won't worry about a difference so small (again, 0.6%).

> laggy when enabling shadows

now, that's the real problem here. shadows shouldn't be this slow, and in fact it is not on my machine.

what GPU do you have?

**Comment by siduck** [comment] 2024-10-10 15:15
![image](https://github.com/user-attachments/assets/832fd4e8-2401-428a-856b-48c7233d184c)

**Comment by siduck** [comment] 2024-10-10 15:17
> does picom-ftlabs still use 10 mb on glx?

No, it uses 170mb too. i think by default it uses xrender.

On Original picom , i get below 10 mb with xrender too! but the shadows make things slow, weird

**Comment by yshui** [comment] 2024-10-10 15:43
does cpu usage go up when picom lags?

**Comment by siduck** [comment] 2024-10-10 16:18
not at all

**Comment by siduck** [comment] 2024-10-10 16:44
also i didnt face the lag on the picom version 11.2, when picom didnt had animations support


https://github.com/user-attachments/assets/cd05e138-ba1a-4ca1-977d-c96f632d2693

**Comment by yshui** [comment] 2024-10-10 17:00
> not at all

does turning off `vsync` and/or `frame-pacing` change anything?

**Comment by yshui** [comment] 2024-10-10 20:41
this is a duplicate of #1349

**Closed as not planned by yshui** 2024-10-10 20:41 UTC
Labels: backend: xrender, performance

**Comment by siduck** [comment] 2024-10-11 00:41
> > not at all
> 
> does turning off `vsync` and/or `frame-pacing` change anything?

unfortunately no

**Comment by siduck** [comment] 2024-11-03 04:24
@yshui  i recently added a new gpu ( was using IGPU before ), now i no longer face this lag
