### ISSUE TITLE
Crashes after some time

### ISSUE THREAD

**Issue by xt1zer** [yshui/compton#143] opened 2019-03-25 11:39 UTC
### Platform
Arch 5.0.4-arch1-1-ARCH

### GPU, drivers, and screen setup
Nvidia Geforce GTX 1070 Ti, nvidia 418.56-2

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 8045 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1070 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 418.56
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 418.56
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 418.56
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
i3-gaps

### Compton version
v6
--diagnostics output:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 8045 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1070 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 418.56
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 418.56
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 418.56
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Compton configuration:
```
# Thank you code_nomad: http://9m.no/ꪯ鵞
# and Arch Wiki contributors: https://wiki.archlinux.org/index.php/Compton

#################################
#
# Backend
#
#################################

# Backend to use: "xrender" or "glx".
# GLX backend is typically much faster but depends on a sane driver.
backend = "glx";

#################################
#
# GLX backend
#
#################################

glx-no-stencil = true;

# GLX backend: Copy unmodified regions from front buffer instead of redrawing them all.
# My tests with nvidia-drivers show a 10% decrease in performance when the whole screen is modified,
# but a 20% increase when only 1/4 is.
# My tests on nouveau show terrible slowdown.
glx-copy-from-front = false;

# GLX backend: Use MESA_copy_sub_buffer to do partial screen update.
# My tests on nouveau shows a 200% performance boost when only 1/4 of the screen is updated.
# May break VSync and is not available on some drivers.
# Overrides --glx-copy-from-front.
# glx-use-copysubbuffermesa = true;

# GLX backend: Avoid rebinding pixmap on window damage.
# Probably could improve performance on rapid window content changes, but is known to break things on some drivers (LLVMpipe).
# Recommended if it works.
# glx-no-rebind-pixmap = true;

# GLX backend: GLX buffer swap method we assume.
# Could be undefined (0), copy (1), exchange (2), 3-6, or buffer-age (-1).
# undefined is the slowest and the safest, and the default value.
# copy is fastest, but may fail on some drivers,
# 2-6 are gradually slower but safer (6 is still faster than 0).
# Usually, double buffer means 2, triple buffer means 3.
# buffer-age means auto-detect using GLX_EXT_buffer_age, supported by some drivers.
# Useless with --glx-use-copysubbuffermesa.
# Partially breaks --resize-damage.
# Defaults to undefined.
#glx-swap-method = "undefined";

#################################
#
# Shadows
#
#################################

# Enabled client-side shadows on windows.
shadow = true;
# The blur radius for shadows. (default 12)
shadow-radius = 5;
# The left offset for shadows. (default -15)
shadow-offset-x = -5;
# The top offset for shadows. (default -15)
shadow-offset-y = -5;
# The translucency for shadows. (default .75)
shadow-opacity = 0.5;

# Set if you want different colour shadows
# shadow-red = 0.0;
# shadow-green = 0.0;
# shadow-blue = 0.0;

# The shadow exclude options are helpful if you have shadows enabled. Due to the way compton draws its shadows, certain applications will have visual glitches
# (most applications are fine, only apps that do weird things with xshapes or argb are affected).
# This list includes all the affected apps I found in my testing. The "! name~=''" part excludes shadows on any "Unknown" windows, this prevents a visual glitch with the XFWM alt tab switcher.
shadow-exclude = [
    "! name~=''",
    "name = 'Notification'",
    "name = 'Plank'",
    "name = 'Docky'",
    "name = 'Kupfer'",
    "name = 'xfce4-notifyd'",
    "name *= 'VLC'",
    "name *= 'compton'",
    "name *= 'Chromium'",
    "name *= 'Chrome'",
    "class_g = 'Firefox' && argb",
    "class_g = 'Conky'",
    "class_g = 'Kupfer'",
    "class_g = 'Synapse'",
    "class_g ?= 'Notify-osd'",
    "class_g ?= 'Cairo-dock'",
    "class_g ?= 'Xfce4-notifyd'",
    "class_g ?= 'Xfce4-power-manager'",
    "_GTK_FRAME_EXTENTS@:c",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];
# Avoid drawing shadow on all shaped windows (see also: --detect-rounded-corners)
shadow-ignore-shaped = false;

#################################
#
# Opacity
#
#################################

inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;

# Dim inactive windows. (0.0 - 1.0)
# inactive-dim = 0.2;
# Do not let dimness adjust based on window opacity.
# inactive-dim-fixed = true;
# Blur background of transparent windows. Bad performance with X Render backend. GLX backend is preferred.
# blur-background = true;
# Blur background of opaque windows with transparent frames as well.
# blur-background-frame = true;
# Do not let blur radius adjust based on window opacity.
blur-background-fixed = false;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

#################################
#
# Fading
#
#################################

# Fade windows during opacity changes.
fading = true;
# The time between steps in a fade in milliseconds. (default 10).
fade-delta = 4;
# Opacity change between steps while fading in. (default 0.028).
fade-in-step = 0.03;
# Opacity change between steps while fading out. (default 0.03).
fade-out-step = 0.03;
# Fade windows in/out when opening/closing
# no-fading-openclose = true;

# Specify a list of conditions of windows that should not be faded.
fade-exclude = [ ];

#################################
#
# Other
#
#################################

# Try to detect WM windows and mark them as active.
mark-wmwin-focused = true;
# Mark all non-WM but override-redirect windows active (e.g. menus).
mark-ovredir-focused = true;
# Use EWMH _NET_WM_ACTIVE_WINDOW to determine which window is focused instead of using FocusIn/Out events.
# Usually more reliable but depends on a EWMH-compliant WM.
use-ewmh-active-win = true;
# Detect rounded corners and treat them as rectangular when --shadow-ignore-shaped is on.
detect-rounded-corners = true;

# Detect _NET_WM_OPACITY on client windows, useful for window managers not passing _NET_WM_OPACITY of client windows to frame windows.
# This prevents opacity being ignored for some apps.
# For example without this enabled my xfce4-notifyd is 100% opacity no matter what.
detect-client-opacity = true;

# Specify refresh rate of the screen.
# If not specified or 0, compton will try detecting this with X RandR extension.
refresh-rate = 0;

# Vertical synchronization: match the refresh rate of the monitor
vsync = true;

# Enable DBE painting mode, intended to use with VSync to (hopefully) eliminate tearing.
# Reported to have no effect, though.
dbe = false;

# Limit compton to repaint at most once every 1 / refresh_rate second to boost performance.
# This should not be used with --vsync drm/opengl/opengl-oml as they essentially does --sw-opti's job already,
# unless you wish to specify a lower refresh rate than the actual value.
#sw-opti = true;

# Unredirect all windows if a full-screen opaque window is detected, to maximize performance for full-screen windows, like games.
# Known to cause flickering when redirecting/unredirecting windows.
unredir-if-possible = false;

# Specify a list of conditions of windows that should always be considered focused.
focus-exclude = [ ];

# Use WM_TRANSIENT_FOR to group windows, and consider windows in the same group focused at the same time.
detect-transient = true;
# Use WM_CLIENT_LEADER to group windows, and consider windows in the same group focused at the same time.
# WM_TRANSIENT_FOR has higher priority if --detect-transient is enabled, too.
detect-client-leader = true;

#################################
#
# Window type settings
#
#################################

wintypes:
{
    tooltip =
    {
        # fade: Fade the particular type of windows.
        fade = true;
        # shadow: Give those windows shadow
        shadow = false;
        # opacity: Default opacity for the type of windows.
        opacity = 0.85;
        # focus: Whether to always consider windows of this type focused.
        focus = true;
    };
};

######################
#
# XSync
# See: https://github.com/yshui/compton/commit/b18d46bcbdc35a3b5620d817dd46fbc76485c20d
#
######################

# Use X Sync fence to sync clients' draw calls. Needed on nvidia-drivers with GLX backend for some users.
xrender-sync-fence = true;

# Autostart config
opacity-rule = [
	"90:class_g = 'URxvt' && focused",
	"60:class_g = 'URxvt' && !focused"
];
```

### Trace
https://pastebin.com/cN5mMthk

### Steps of reproduction
1. "compton &" in bash
2. after some time realising that the effects don't work, terminal output is:
```
compton: ../compton/src/win.c:1623: map_win: Assertion `!win_is_focused_real(ps, w)' failed.

[1]  + 3362 abort (core dumped)  compton
```

What's stack trace, and where's the dump?

**Comment by yshui** [comment] 2019-03-25 12:17
Is that the only terminal output?

**Comment by xt1zer** [comment] 2019-03-25 12:18
> Is that the only terminal output?
> 
> How often does this happen?

Yes. Each time after, like, 3 minutes being busy

**Comment by yshui** [comment] 2019-03-25 12:38
Can you run `compton --log-level=trace` and post the output?

**Comment by xt1zer** [comment] 2019-03-25 13:06
> Can you run `compton --log-level=trace` and post the output?

This takes longer that I expect it to, I'll write back when it happens next time with a log

**Comment by xt1zer** [comment] 2019-03-25 14:09
Surprisingly, it never crashed since your response. I'll try to reproduce the issue with active and daemon (compton -b) processes

**Comment by xt1zer** [comment] 2019-03-25 14:18
> Can you run `compton --log-level=trace` and post the output?

Hey, I figured out that it at least crashes when a "Download" popup window of Firefox appears (floating), this happened now a few times. OP updated with the trace

**Comment by sveatlo** [comment] 2019-03-25 14:44
I have exactly the same problem on arch with i3-gaps, but I cannot reproduce the bug with firefox's "Download" popup window or any other floating window.

This is my terminal output without trace log level:
```
[ 03/25/2019 14:38:58.307 glx_bind_pixmap ERROR ] Failed to query info of pixmap 0x04e2ea7e.
[ 03/25/2019 14:38:58.307 paint_one ERROR ] Failed to bind texture for window 0x07200372.
[ 03/25/2019 14:38:58.307 paint_one ERROR ] Window 0x07200372 is missing painting data.
compton: ../compton/src/win.c:1623: map_win: Assertion `!win_is_focused_real(ps, w)' failed.
[1]    12283 abort (core dumped)  compton --config ~/.i3/compton.conf
```

**Comment by yshui** [comment] 2019-03-25 14:49
@sveatlo Can you try again with `--log-level=trace`? Thanks.

**Comment by sveatlo** [comment] 2019-03-25 14:53
I was just about to post it :D https://termbin.com/k3sh

**Comment by sveatlo** [comment] 2019-03-25 14:54
also my config (very simple): https://termbin.com/j1dy

**Comment by yshui** [comment] 2019-03-25 15:11
@sveatlo @xt1zer Should be fixed in `next` (also in `stable/6`)

**Comment by yshui** [comment] 2019-03-25 21:43
Can you confirm?

**Comment by sveatlo** [comment] 2019-03-26 13:44
I've been running from a git build since your comment without any problems. Though I wasn't able to forcefully replicate the issue before, I believe it is solved.

**Comment by yshui** [comment] 2019-03-26 14:00
I'm closing this then. Please reopen if it happens again

**Closed by yshui** 2019-03-26 14:00 UTC
Labels: bug

**Comment by xt1zer** [comment] 2019-03-26 14:58
> I'm closing this then. Please reopen if it happens again

Oh hey, I wasn't home til now. By "confirm" did you mean if the commit fixed the issue? When should I expect an update in Arch repos?

**Comment by clawoflight** [comment] 2019-03-27 16:55
Can you release a new version, since this fixes a deal-braking bug?

**Comment by yshui** [comment] 2019-03-27 18:59
@clawoflight I don't understand how this is deal-breaking. Distros shouldn't be using debug build, and release builds shouldn't include asserts.

**Comment by yshui** [comment] 2019-03-27 19:07
ping @xyproto.

Is ArchLinux not doing release builds of compton?

**Comment by clawoflight** [comment] 2019-03-27 20:38
@yshui doesn't look like it:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/compton

And this is the meson wrapper:

https://git.archlinux.org/svntogit/packages.git/tree/trunk/arch-meson?h=packages/meson

**Comment by yshui** [comment] 2019-03-27 20:57
@clawoflight the meson wrapper uses `--buildtype plain` and does not enable `b_ndebug`. So that's why.

cc @xyproto

**Comment by clawoflight** [comment] 2019-03-28 08:42
Thanks for the replies! I opened a bug on the Arch side: https://bugs.archlinux.org/task/62166

**Comment by xyproto** [comment] 2019-03-28 10:01
See also:

https://github.com/mesonbuild/meson/pull/5143

**Comment by xt1zer** [comment] 2019-03-28 15:49
Just received an update and the issue seemed to never appear again. Thanks for your support!
