### ISSUE TITLE
Leave images in spaces when moving window using sxhkd

### ISSUE THREAD

**Issue by tuyenpm9** [yshui/compton#22] opened 2018-10-18 04:53 UTC
### Platform
newest archlinux system, up-to-date

### GPU, drivers, and screen setup
intel hd630

### Compton version
`compton --version`:
v3-rc1-3-gf84336a

### Compton configuration:
I tested with:
```
compton --config /dev/null --backend glx &
```

### Steps of reproduction
setup sxhkd with `wmv` and you will see images saved in background of spaces that the window is just moved out, like not respond of windows xp when you moving not responding window using mouse.

### Expected behavior
Robust when moving windows, no leave images in spaces after moving windows.

**Comment by yshui** [comment] 2018-10-18 08:11
Duplicate of #19 #20. Fixed is v3-rc2.

**Closed by yshui** 2018-10-18 08:11 UTC
