### ISSUE TITLE
MATE+Compton badly move Gnome apps with keyboard shortcuts

### ISSUE THREAD

**Issue by l3nn4rt** [yshui/compton#15] opened 2018-10-04 13:12 UTC
I submitted a bug at https://github.com/mate-desktop/marco/issues/414, but it may be related to compton, so I'll leave this here.

### Platform
Arch Linux x86_64

### GPU, drivers, and screen setup
Intel HD Graphics 630, i915 driver, one monitor

### Compton version
v2.0

### Compton configuration:
```
$  grep -vE '^\s*(#|$)' /etc/xdg/compton.conf
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
glx-swap-method = "undefined";
shadow = true;
no-dnd-shadow = true;
no-dock-shadow = true;
clear-shadow = true;
shadow-radius = 5;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.5;
shadow-exclude = [
    "! name~=''",
    "name = 'Notification'",
    "name = 'Plank'",
    "name = 'Docky'",
    "name = 'Kupfer'",
    "name = 'xfce4-notifyd'",
    "name *= 'VLC'",
    "name *= 'compton'",
    "name *= 'Chromium'",
    "name *= 'Chrome'",
    "class_g = 'Conky'",
    "class_g = 'Kupfer'",
    "class_g = 'Synapse'",
    "class_g ?= 'Notify-osd'",
    "class_g ?= 'Cairo-dock'",
    "class_g ?= 'Xfce4-notifyd'",
    "class_g ?= 'Xfce4-power-manager'",
    "_GTK_FRAME_EXTENTS@:c"
];
shadow-ignore-shaped = false;
menu-opacity = 1;
inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
alpha-step = 0.06;
blur-background-fixed = false;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];
fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];
mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = "opengl-swc";
dbe = false;
paint-on-overlay = true;
sw-opti = true;
unredir-if-possible = true;
focus-exclude = [ ];
detect-transient = true;
detect-client-leader = true;
wintypes:
{
    tooltip =
    {
        fade = true;
        shadow = false;
        opacity = 0.85;
        focus = true;
    };
};
```

### Steps of reproduction
1. install MATE 1.20
2. check mate-desktop issue above

### Expected behavior
check mate-desktop issue above
### Current Behavior
check mate-desktop issue above

**Comment by yshui** [comment] 2018-10-04 13:40
@l3nn4rt Did you check if this problem still happens without compton?

**Comment by l3nn4rt** [comment] 2018-10-10 08:57
it happens with `compton` and `marco (adaptive compositor)` , but not with `compiz` 0.9 nor without compositor.

**Comment by yshui** [comment] 2018-10-10 09:31
@l3nn4rt I think this is a window manager (macro) bug. compiz replaces your window manager so of course that works.

I will leave this open until it is confirmed upstream.

**Comment by yshui** [comment] 2019-08-02 22:15
Closing because it's fixed upstream

https://github.com/mate-desktop/marco/pull/531

**Closed by yshui** 2019-08-02 22:15 UTC
Labels: upstream
