### ISSUE TITLE
Black window corners under 'xrender' backend

### ISSUE THREAD

**Issue by XoDefender** [yshui/compton#1142] opened 2023-10-27 09:45 UTC
Windows with rounded corners have black outlines. The 9th version of picom did not have this problem - window with rounded corners were painted just like under 'glx' backend 
![изображение](https://github.com/yshui/picom/assets/90552397/80a05002-fc0a-4147-9a2d-e09909cf7b21)

**Comment by XoDefender** [comment] 2023-10-27 10:59
It is because of render happening in xrender.c instead of render.c - so may be fixed 1) by setting legacy_backend to true if it is xrender 2) changing the way xrender compose_impl work

**Comment by absolutelynothelix** [comment] 2023-10-27 14:51
closing as duplicate of #808.

**Closed as not planned by absolutelynothelix** 2023-10-27 14:51 UTC
Labels: duplicate
