### ISSUE TITLE
Very bad performance and lag in VirtualBox

### ISSUE THREAD

**Issue by tiiiecherle** [yshui/compton#220] opened 2019-08-09 07:24 UTC
### Platform
archlinux in virtualbox

### GPU, drivers, and screen setup
vboxvideo

### Environment
openbox

### Compton version
latest 7.1-1

### Compton configuration:
```
# running with empty config file
```

### Steps of reproduction
Login to a desktop environment and start compton &

### Expected behavior
no lag, no performance issues

### Current Behavior
the whole desktop gets almost unusable with a really bad lag. right click for opening open box menu not possible due to too much lag.

### Stack trace
---

### Other details
latest version without this issue is 6.2-2 in archlinux. downgrading solves the issue.

**Comment by yshui** [comment] 2019-08-09 22:43
Duplicate of #40

**Closed by yshui** 2019-08-09 22:43 UTC
