### ISSUE TITLE
Blur effect produces strange effects in terminal window

### ISSUE THREAD

**Issue by vaskark** [yshui/compton#194] opened 2019-06-21 18:51 UTC
Hi. I'm trying to get blurring to work for me. And it mostly does, except for some strange side-effects in terminal windows. I tried to include all relevant information.

### Platform

Ubuntu 19.04 x86_64

### GPU, drivers, and screen setup

```
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)  (0x5916)
    Version: 19.0.2
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.0.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.0.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
### Environment
```
$ i3 -v
i3 version 4.16.1-183-gd32fc328 (2019-06-17, branch "gaps-next") © 2009 Michael Stapelberg and contributors

```

### Compton version
```
$ compton --version
compton (v6-rc1-168-g5a034ea)
```

```
$ compton --diagnostics --experimental-backends
**Version:** v6-rc1-168-g5a034ea

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/vaskark/.config/compton.conf

### Drivers (inaccurate):

modesetting  
```

### Compton configuration:
```
# Shadow
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
log-level = "warn";
# log-file = "/path/to/your/log/file";
# shadow-opacity = 0.7;
# shadow-red = 0.0;
# shadow-green = 0.0;
# shadow-blue = 0.0;
shadow-exclude = [
	"name = 'Notification'",
	"class_g = 'Conky'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'Cairo-clock'",
	"_GTK_FRAME_EXTENTS@:c"
];
# shadow-exclude = "n:e:Notification";
# shadow-exclude-reg = "x10+0+0";
# xinerama-shadow-crop = true;

# Opacity
inactive-opacity = 0.95;
# active-opacity = 0.8;
frame-opacity = 0.95;
inactive-opacity-override = false;
# inactive-dim = 0.2;
# inactive-dim-fixed = true;
# blur-background = true;
# blur-background-frame = true;
# blur-kern = "3x3gaussian";
# blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
# blur-background-fixed = true;
blur-background-exclude = [
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"_GTK_FRAME_EXTENTS@:c"
];

blur:
{
  method = "gaussian";
  size = 10;
  deviation = 5.0;
};

opacity-rule = [
	"100:class_g = 'vlc'",
	"100:class_g = 'YACReader'",
	"100:class_g = 'Zathura'",
	"100:class_g = 'evince'",
        "100:class_g = 'Gnome-mpv'"
];

# Fading
fading = true;
# fade-delta = 30;
fade-in-step = 0.10;
fade-out-step = 0.10;
# no-fading-openclose = true;
# no-fading-destroyed-argb = true;
fade-exclude = [ ];

# Other
backend = "glx";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
# use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = true;
# sw-opti = true;
# unredir-if-possible = true;
# unredir-if-possible-delay = 5000;
# unredir-if-possible-exclude = [ ];
focus-exclude = [ "class_g = 'Cairo-clock'" ];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];
# resize-damage = 1;

# GLX backend
#glx-no-stencil = true;
#glx-no-rebind-pixmap = true;
# xrender-sync-fence = true;
use-damage = true;

# Window type settings
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.95; focus = true; full-shadow = false; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.95; }
  dropdown_menu = { opacity = 0.95; }
};
```

### Steps of reproduction

`compton --experimental-backends
`
### Expected behavior

`Blurring with no strange artifacts.`

### Current Behavior

See [here](https://i.imgur.com/bvbTMW9.png).

### Conclusion
Hopefully someone can shed some light on this issue.
Thanks!

**Comment by yshui** [comment] 2019-06-24 09:21
Probably a duplicate of #50

**Comment by yshui** [comment] 2019-06-24 09:22
Does this happen if you set `use-damage = false`?

**Comment by vaskark** [comment] 2019-06-24 15:52
> Does this happen if you set `use-damage = false`?

I just changed it to false and it worked. Thank you so much.

**Comment by vaskark** [comment] 2019-06-25 14:48
Also, a question: is it just terminal windows that can experience the blurring effect? Just wondering about gtk windows, etc.

**Comment by yshui** [comment] 2019-06-26 14:46
@vaskark all semi-transparent window should have a blurred background.

> I just changed it to false and it worked. 

That's a workaround, I'm working on a proper fix right now.

**Comment by vaskark** [comment] 2019-06-26 14:57
Thanks, @yshui. Here's a shot of my desktop comparing blurring effects: [https://i.imgur.com/axx9dz7.png](url)

**Comment by yshui** [comment] 2019-07-26 01:34
This should be fixed in `next`, if you use `--experimental-backends`

**Closed** 2019-07-26 01:34 UTC
